global using i8 = sbyte;
global using u8 = byte;
global using i16 = short;
global using u16 = ushort;
global using i32 = int;
global using u32 = uint;
global using i64 = long;
global using u64 = ulong;
global using f32 = float;
global using f64 = double;
global using static SDL2.SDL;
global using static src.Debugging.Logger;
global using static src.Dev.GlobalUtility;